#   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci = [1,2]
f_sum = 2
f_next = 0
limit = 4000000
i = 2

while f_next < limit:
    f_next = fibonacci[i - 2] + fibonacci[i - 1]
    fibonacci.append(f_next)
    if(f_next % 2 == 0):
        f_sum += f_next
    i += 1
    
print(f_sum)

